name: NEW Deploy ADF Resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  SOURCE_ADF: ${{ vars.AZURE_DATA_FACTORY_DEV }}

jobs:       
  deploy-qa:
    runs-on: ubuntu-latest
    
    environment:
      name: QA
      url: https://portal.azure.com/
      
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"
  
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
    
      # - name: Wait for QA Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
      
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Run Pre-deployment script
        run: |
          try {
            ./PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
            -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
            -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
            -predeployment $true `
            -deleteDeployment $false
          } catch {
            Write-Error "Pre-deployment script failed: $_"
            exit 1
          }
        shell: pwsh

      - name: Deploy to QA
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_QA.json
          mode: incremental

      - name: Run Post-deployment script
        run: |
          try {
            if ($null -ne $deploymentsToConsider -and $deploymentsToConsider.Count -gt 0) {
              $deploymentName = $deploymentsToConsider[0].DeploymentName
              # proceed with deletion
              ./PrePostDeploymentScript.Ver2.ps1 `
                -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
                -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
                -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
                -predeployment $false `
                -deleteDeployment $true
            } else {
              Write-Warning "No deployments found to delete in resource group $ResourceGroupName"
            }
          } catch {
            Write-Error "Post-deployment script failed: $_"
            exit 1
          }
        shell: pwsh

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    
    environment:
      name: PRD
      url: https://portal.azure.com/
      
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"
        
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          
      # - name: Wait for Prod Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
        
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Pre-deployment script
        run: |
          try {
            ./PrePostDeploymentScript.Ver2.ps1 `
            -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
            -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
            -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
            -predeployment $true `
            -deleteDeployment $false
          } catch {
            Write-Error "Pre-deployment script failed: $_"
            exit 1
          }
        shell: pwsh
        
      - name: Deploy to Prod
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_PRD.json
          mode: incremental
      
      - name: Run Post-deployment script
        run: |
          try {
            if ($null -ne $deploymentsToConsider -and $deploymentsToConsider.Count -gt 0) {
              $deploymentName = $deploymentsToConsider[0].DeploymentName
              # proceed with deletion
              ./PrePostDeploymentScript.Ver2.ps1 `
                -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
                -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
                -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
                -predeployment $false `
                -deleteDeployment $true
            } else {
              Write-Warning "No deployments found to delete in resource group $ResourceGroupName"
            }
          } catch {
            Write-Error "Pre-deployment script failed: $_"
            exit 1
          }
        shell: pwsh
