name: NEW Deploy ADF Resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  SOURCE_ADF: ${{ vars.AZURE_DATA_FACTORY_DEV }}

jobs:       
  deploy-qa:
    runs-on: ubuntu-latest
    
    environment:
      name: QA
      url: https://portal.azure.com/
    
    # env:
    #   SOURCE_ADF: ${{ vars.AZURE_DATA_FACTORY_DEV }}
  
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"
  
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
    
      # - name: Wait for QA Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # - name: List all files recursively
      #   run: find . -type f

      - name: Verify PrePostDeploymentScript exists
        run: test -f ./PrePostDeploymentScript.Ver2.ps1 && echo "Script found" || (echo "Script missing" && exit 1)

      - name: Verify ARMTemplateForFactory exists
        run: test -f ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json && echo "Script found" || (echo "Script missing" && exit 1)
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
      
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Run Pre-deployment script
        run: |
          ./PrePostDeploymentScript.Ver2.ps1 `
          -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
          -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
          -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
          -predeployment $true `
          -deleteDeployment $false
        shell: pwsh

      - name: Deploy to QA
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_QA.json
          mode: incremental

      - name: Run Post-deployment script
        run: |
          ./PrePostDeploymentScript.Ver2.ps1 `
          -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
          -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
          -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
          -predeployment $false `
          -deleteDeployment $true
        shell: pwsh

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    
    environment:
      name: PRD
      url: https://portal.azure.com/
    
    # env:
    #  SOURCE_ADF: ${{ vars.AZURE_DATA_FACTORY_DEV }}
      
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"

      - name: Verify PrePostDeploymentScript exists
        run: test -f ./PrePostDeploymentScript.Ver2.ps1 && echo "Script found" || (echo "Script missing" && exit 1)
        
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          
      # - name: Wait for Prod Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
        
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run Pre-deployment script
        run: |
          ./PrePostDeploymentScript.Ver2.ps1 `
          -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
          -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
          -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
          -predeployment $true `
          -deleteDeployment $false
        shell: pwsh
        
      - name: Deploy to Prod
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_PRD.json
          mode: incremental
      
      - name: Run Post-deployment script
        run: |
          ./PrePostDeploymentScript.Ver2.ps1 `
          -armTemplate "./$env:SOURCE_ADF/ARMTemplateForFactory.json" `
          -ResourceGroupName "${{ vars.AZURE_RESOURCE_GROUP }}" `
          -DataFactoryName "${{ vars.AZURE_DATA_FACTORY }}" `
          -predeployment $false `
          -deleteDeployment $true
        shell: pwsh
