name: NEW Deploy ADF Resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  SOURCE_ADF: ${{ vars.AZURE_DATA_FACTORY_DEV }}

jobs:       
  deploy-qa:
    runs-on: ubuntu-latest
    
    environment:
      name: QA
      url: https://portal.azure.com/
      
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"
  
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
    
      # - name: Wait for QA Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
      
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy to QA
        uses: Azure/data-factory-deploy-action@v2.1.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_QA.json

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    
    environment:
      name: PRD
      url: https://portal.azure.com/
      
    steps:
      - name: Using ARM Template from source ADF instance
        run: echo "Source ADF instance is $SOURCE_ADF"
        
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          
      # - name: Wait for Prod Approval
      #  uses: hmarr/auto-approve-action@v2
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install Az PowerShell module
        run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        shell: pwsh
        
      - name: Login to Azure
        uses: azure/login@v1
        with:       
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
        
      - name: Deploy to Prod
        uses: Azure/data-factory-deploy-action@v2.1.0
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          dataFactoryName: ${{ vars.AZURE_DATA_FACTORY }}
          armTemplateFile: ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json
          armTemplateParametersFile: ./ARMTemplateParameters_PRD.json
          # mode: incremental
      
